//go:build !ignore_autogenerated

package v1alpha1

import (
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// DeepCopyInto copies all properties of TetherLease into another TetherLease instance.
func (in *TetherLease) DeepCopyInto(out *TetherLease) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

// DeepCopy creates a deep copy of TetherLease.
func (in *TetherLease) DeepCopy() *TetherLease {
	if in == nil {
		return nil
	}
	out := new(TetherLease)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *TetherLease) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of TetherLeaseList into another TetherLeaseList instance.
func (in *TetherLeaseList) DeepCopyInto(out *TetherLeaseList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]TetherLease, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

// DeepCopy creates a deep copy of TetherLeaseList.
func (in *TetherLeaseList) DeepCopy() *TetherLeaseList {
	if in == nil {
		return nil
	}
	out := new(TetherLeaseList)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyObject implements runtime.Object.
func (in *TetherLeaseList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

// DeepCopyInto copies all properties of TetherLeaseSpec.
func (in *TetherLeaseSpec) DeepCopyInto(out *TetherLeaseSpec) {
	*out = *in
}

// DeepCopy creates a deep copy of TetherLeaseSpec.
func (in *TetherLeaseSpec) DeepCopy() *TetherLeaseSpec {
	if in == nil {
		return nil
	}
	out := new(TetherLeaseSpec)
	in.DeepCopyInto(out)
	return out
}

// DeepCopyInto copies all properties of TetherLeaseStatus.
func (in *TetherLeaseStatus) DeepCopyInto(out *TetherLeaseStatus) {
	*out = *in
	if in.ExpiresAt != nil {
		in, out := &in.ExpiresAt, &out.ExpiresAt
		*out = (*in).DeepCopy()
	}
}

// DeepCopy creates a deep copy of TetherLeaseStatus.
func (in *TetherLeaseStatus) DeepCopy() *TetherLeaseStatus {
	if in == nil {
		return nil
	}
	out := new(TetherLeaseStatus)
	in.DeepCopyInto(out)
	return out
}
